texnikum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('texnikumapp.urls')),
    path('', include('talabaapp.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

texnikumapp/urls.py
from django.urls import path
from .views import ( home, texnikum_tarix, rahbariyat, kafedralar, markaz_va_bulimlar, aloqalar, yangiliklar, elonlar, 
                    bitta_elon, bitta_yangilik, qonunlar, farmonlar, qarorlar, nizomlar_va_qoidalar, fotolar, vediolar )

app_name = 'texapp'

urlpatterns = [
    path('', home, name = 'home'),
    # texnikum
    path('texnikum/tarix', texnikum_tarix, name = 'texnikum_tarix'),
    path('texnikum/rahbariyat', rahbariyat, name = 'rahbariyat'),
    path('texnikum/kafedralar', kafedralar, name = 'kafedralar'),
    path('texnikum/markaz-va-bulimlar', markaz_va_bulimlar, name = 'markaz_va_bulimlar'),
    path('texnikum/aloqalar', aloqalar, name = 'aloqalar'),
    # yangiliklar
    path('yangiliklar/yangiliklar', yangiliklar, name = 'yangiliklar'),
    path('yangiliklar/yangilik/<int:pk>', bitta_yangilik, name = 'yangilik'),
    path('yangiliklar/elonlar', elonlar, name = 'elonlar'),
    path('yangiliklar/elon/<int:pk>', bitta_elon, name = 'elon'),
    # hujjatlar
    path('hujjatlar/qonunlar', qonunlar, name = 'qonunlar'),
    path('hujjatlar/farmonlar', farmonlar, name = 'farmonlar'),
    path('hujjatlar/qarorlar', qarorlar, name = 'qarorlar'),
    path('hujjatlar/nizomlar-va-qoidalar', nizomlar_va_qoidalar, name = 'nizomlar_va_qoidalar'),
    # galeriya
    path('galeriya/fotolar', fotolar, name = 'fotolar'),
    path('galeriya/vediolar', vediolar, name = 'vediolar'),

]

texnikumapp/models.py
from django.db import models

# Create your models here.
class Rahbariyat(models.Model):
	lavozim = models.CharField(max_length=50)
	ism_familiya_sharf = models.CharField(max_length=50)
	rasm = models.ImageField(upload_to = 'rahbarlar/')
	qabul_vaqti = models.CharField(max_length=30)
	telefon = models.IntegerField()
	elektrion_pochta = models.EmailField()
	vazifalar = models.TextField()
	biografiya = models.TextField()

	def __str__(self):
		return self.lavozim + '  ' + self.ism_familiya_sharf


class Kafedra(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name

class KafedraMalumot(models.Model):
	nomi = models.ForeignKey(Kafedra, on_delete = models.CASCADE)
	mudir_ism_familiya_sharf = models.CharField(max_length=50)
	rasm = models.ImageField(upload_to = 'kafedra/')
	qabul_vaqti = models.CharField(max_length=30)
	telefon = models.IntegerField()
	elektrion_pochta = models.EmailField()
	biografiya = models.TextField()
	kafedra_haqida = models.TextField()

	def __str__(self):
		return self.nomi + '  ' + self.mudir_ism_familiya_sharf

class BulimVaMarkazlar(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name

class BulimVaMarkazlarMalumot(models.Model):
	nomi = models.ForeignKey(BulimVaMarkazlar, on_delete = models.CASCADE)
	ism_familiya_sharf = models.CharField(max_length=50)
	rasm = models.ImageField(upload_to = 'bulimlar/')
	qabul_vaqti = models.CharField(max_length=30)
	telefon = models.IntegerField()
	elektrion_pochta = models.EmailField()
	biografiya = models.TextField()
	kafedra_haqida = models.TextField()

	def __str__(self):
		return self.ism_familiya_sharf

class Yangiliklar(models.Model):
	sarlavha = models.CharField(max_length=200)
	rasm = models.ImageField(upload_to='yangiliklar/')
	matn = models.TextField()
	fayl_yul = models.URLField(blank=True)
	sana = models.DateField(auto_now_add=True)
	yan_kurilgan = models.IntegerField(default=0)

	def __str__(self):
		return self.sarlavha

class Elonlar(models.Model):
	sarlavha = models.CharField(max_length=200)
	rasm = models.ImageField(upload_to='elonlar/')
	matn = models.TextField()
	fayl_yul = models.URLField(blank=True)
	sana = models.DateField(auto_now_add=True)
	elon_kurilgan = models.IntegerField(default=0)


	def __str__(self):
		return self.sarlavha

class Fotolar(models.Model):
	name = models.CharField(max_length=100)
	rasmlar = models.ImageField(upload_to='fotolar/')
	# sana = models.DateField(auto_now_add=True)

texnikumapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Yangiliklar, Elonlar, Fotolar
from django.core.paginator import Paginator, EmptyPage

# Create your views here.

def home(request):
	fotolar = Fotolar.objects.order_by('-id')[:6]
	elon1 = Elonlar.objects.order_by('-id')[:1]
	elonlar = Elonlar.objects.order_by('-id')[1:3]
	yangilik1 = Yangiliklar.objects.order_by('-id')[:1]
	yangiliklar = Yangiliklar.objects.order_by('-id')[1:3]

	context = {
		'fotolar':fotolar,
		'elon1':elon1,
		'elonlar':elonlar,
		'yangilik1':yangilik1,
		'yangiliklar':yangiliklar,
	}
	return render(request, 'home.html', context)

def texnikum_tarix(request):
	return render(request, 'texnikum/texnikum_tarix.html')

def rahbariyat(request):
	return render(request, 'texnikum/rahbariyat.html')

def kafedralar(request):
	return render(request, 'texnikum/kafedralar.html')

def markaz_va_bulimlar(request):
	return render(request, 'texnikum/markaz_va_bulimlar.html')

def aloqalar(request):
	return render(request, 'texnikum/aloqalar.html')

def fotolar(request):
	return render(request, 'galeriya/fotolar.html')

def vediolar(request):
	return render(request, 'galeriya/vediolar.html')

def yangiliklar(request):
	yangiliklar = Yangiliklar.objects.all()
	pgn = Paginator(yangiliklar, 2)
	page_nums = request.GET.get('page',1)
	try:
		page = pgn.page(page_nums)
	except EmptyPage:
		page = pgn.page(1)
	context = {
		'yangiliklar':page
	}
	return render(request, 'yangiliklar/yangiliklar.html', context)

def bitta_yangilik(request, pk):
	yangilik = get_object_or_404(Yangiliklar, id=pk)
	yangilik.yan_kurilgan = yangilik.yan_kurilgan + 1
	yangilik.save()
	return render(request, 'yangiliklar/yangilik.html', {'yangilik':yangilik})

def elonlar(request):
	elonlar = Elonlar.objects.all()
	pgn = Paginator(elonlar, 2)
	page_nums = request.GET.get('page', 1)
	try:
		page = pgn.page(page_nums)
	except EmptyPage:
		page = pgn.page(1)
	context = {
		'elonlar':page
	}
	return render(request, 'yangiliklar/elonlar.html', context)

def bitta_elon(request, pk):
	elon = get_object_or_404(Elonlar, id=pk)
	elon.elon_kurilgan = elon.elon_kurilgan + 1
	elon.save()

	return render(request, 'yangiliklar/elon.html', {'elon':elon})
	
def qonunlar(request):
	return render(request, 'hujjatlar/qonunlar.html')

def farmonlar(request):
	return render(request, 'hujjatlar/farmonlar.html')

def qarorlar(request):
	return render(request, 'hujjatlar/qarorlar.html')

def nizomlar_va_qoidalar(request):
	return render(request, 'hujjatlar/nizomlar_va_qoidalar.html')

texnikumapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="">

<head>
  <title>Texnikum</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <link href="{% static 'styles/layout.css' %}" rel="stylesheet" type="text/css" media="all">
</head>

<body id="top">
  <div class="wrapper row0">
    <div id="topbar" class="hoc clear">
      <div class="fl_left">
        <ul class="nospace">
          <li><a href="{% url 'texapp:home' %}"><i class="fas fa-home fa-lg"></i></a></li>
          <li><a href="#">Biz haqimizda</a></li>
          <li><a href="#">Bog'lanish</a></li>
          <li><a href="#">Til</a></li>
        </ul>
      </div>
      <div class="fl_right">
        <ul class="nospace">
          <li><i class="fas fa-phone rgtspace-5"></i>+998 97 927 69 23</li>
          <li><i class="fas fa-envelope rgtspace-5"></i>sam_texnikum@email.com</li>
        </ul>
      </div>
      <!-- ################################################################################################ -->
    </div>
  </div>
  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
  <div class="wrapper row1">
    <header id="header" class="hoc clear">
      <!-- ################################################################################################ -->
      <div id="logo" class="one_half first">
        <h1 class="logoname"><a href="{% url 'texapp:home' %}"><span>SamDU</span>Texnikum</a></h1>
      </div>
      <div class="one_half">
        <ul class="nospace clear">
          <li class="one_half first">
            <div class="block clear"><i class="fas fa-phone"></i> <span><strong class="block">Murojaat uchun:</strong>
                +998 97 927 69 23</span> </div>
          </li>
          <li class="one_half">
            <div class="block clear"><i class="far fa-clock"></i> <span><strong class="block"> Dush. - Shan.:</strong>
                08.00am - 18.00pm</span> </div>
          </li>
        </ul>
      </div>
      <!-- ################################################################################################ -->
    </header>
    <nav id="mainav" class="hoc clear">
      <!-- ################################################################################################ -->
      <ul class="clear">
        <li class="active"><a href="{% url 'texapp:home' %}">Bosh sahifa</a></li>
        <li><a class="drop" href="#">texnikum</a>
          <ul>
            <li class="menu-top"><a href="{% url 'texapp:texnikum_tarix' %}">texnikum tarixi</a></li>
            <li class="menu-top"><a href="{% url 'texapp:rahbariyat' %}">raxbariyat</a></li>
            <li class="menu-top"><a href="{% url 'texapp:kafedralar' %}">kafediralar</a></li>
            <li class="menu-top"><a href="{% url 'texapp:markaz_va_bulimlar' %}">markaz va bo'limlar</a></li>
            <li class="menu-top"><a href="{% url 'texapp:aloqalar' %}">aloqalar</a></li>
          </ul>
        </li>
        <li><a class="drop" href="#">yangiliklar</a>
          <ul>
            <li class="menu-top"><a href="{% url 'texapp:yangiliklar' %}">yangiliklar</a></li>
            <li class="menu-top"><a href="{% url 'texapp:elonlar' %}">e'lonlar</a></li>
          </ul>
        </li>
        <li><a class="drop" href="#">talabalar</a>
          <ul>
            <li class="menu-top"><a href="{% url 'yuriqnoma' %}">yo'riqnoma</a></li>
            <li class="menu-top"><a href="{% url 'dars_jadval' %}">dars jadvali</a></li>
            <li class="menu-top"><a href="{% url 'reting' %}">davomat</a></li>
            <li class="menu-top"><a href="{% url 'iqtidorli_talabalar' %}">ixtidorli talabalar</a></li>
          </ul>
        </li>
        <li><a class="drop" href="#">abituriyent</a>
          <ul>
            <li class="menu-top"><a href="{% url 'eslatma' %}">eslatma</a></li>
            <li class="menu-top"><a href="{% url 'qabul_kvota' %}">qabul nizomi</a></li>
            <li class="menu-top"><a href="{% url 'qabul_nizom' %}">qabul kvotasi</a></li>
            <li class="menu-top"><a href="#">hujjatlar to'plami</a></li>
            <li class="menu-top"><a href="#">imtihon fanlari ro'yxati</a></li>
          </ul>
        </li>
        <li><a class="drop" href="#">hujjatlar</a>
          <ul>
            <li class="menu-top"><a href="{% url 'texapp:qonunlar' %}">qonunlar</a></li>
            <li class="menu-top"><a href="{% url 'texapp:farmonlar' %}">farmonlar</a></li>
            <li class="menu-top"><a href="{% url 'texapp:qarorlar' %}">qarorlar</a></li>
            <li class="menu-top"><a href="{% url 'texapp:nizomlar_va_qoidalar' %}">nizomlar va qoidalar</a></li>
          </ul>
        </li>
        <li><a class="drop" href="#">galeriya</a>
          <ul>
            <li class="menu-top"><a href="{% url 'texapp:fotolar' %}">fotogalereya</a></li>
            <li class="menu-top"><a href="{% url 'texapp:vediolar' %}">videogalereya</a></li>
          </ul>
        </li>
      </ul>
      <!-- ################################################################################################ -->
    </nav>
  </div>

  {% block content %}

  {% endblock %}


  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
  <div class="wrapper gradient">
    <section id="cta" class="hoc container clear">
      <!-- ################################################################################################ -->
      <div class="sectiontitle">
        <h6 class="heading">foydali saytlar</h6>
      </div>
      <!-- <ul class="nospace clear">
        <li class="one_third first">
          <div class="block clear">
            <img src="images/demo/3.png" alt="">
          </div>
        </li>
        <li class="one_third">
          <div class="block clear">
            <img src="images/demo/4.png" alt="">
          </div>
        </li>
        <li class="one_third">
          <div class="block clear">
            <img src="images/demo/5.png" alt="">
          </div>
        </li>
      </ul> -->
      <div class="">
        <p class="mySlides"  style="width:100%">Slider1</p>
        <p class="mySlides"  style="width:100%">Slider2</p>
        <p class="mySlides"  style="width:100%">Slider3</p>
        <p class="mySlides"  style="width:100%">Slider4</p>

      
        <button class="w3-button w3-black w3-display-left" onclick="plusDivs(-1)">&#10094;</button>
        <button class="w3-button w3-black w3-display-right" onclick="plusDivs(1)">&#10095;</button>
      </div>
      
      <script>
      var slideIndex = 1;
      showDivs(slideIndex);
      
      function plusDivs(n) {
        showDivs(slideIndex += n);
      }
      
      function showDivs(n) {
        var i;
        var x = document.getElementsByClassName("mySlides");
        if (n > x.length) {slideIndex = 1}
        if (n < 1) {slideIndex = x.length}
        for (i = 0; i < x.length; i++) {
          x[i].style.display = "none";  
        }
        x[slideIndex-1].style.display = "block";  
      }
      </script>
      <!-- ################################################################################################ -->
    </section>
  </div>
  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
  <div class="wrapper row4">
    <footer id="footer" class="hoc clear">
      <!-- ################################################################################################ -->
      <div class="one_third first">
        <h4 class="heading">Bizning manzil</h4>
        <iframe
          src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5313.955385319563!2d67.09030063567519!3d39.700406386410016!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3f4d23880f0ffaff%3A0xbe69eb6bf46964b1!2sJomboy%20maishiy%20xizmat%20kasb-hunar%20kolleji!5e0!3m2!1sen!2s!4v1604249186547!5m2!1sen!2s"
          width="350" height="350" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false"
          tabindex="0"></iframe>
      </div>
      <div class="one_third">
        <h4 class="heading">Yordamchi menyu</h4>
        <ul class="nospace linklist">
          <li class="yordamchi"><a href="#">bosh sahima</a></li>
          <li class="yordamchi"><a href="#">texnikum</a></li>
          <li class="yordamchi"><a href="#">yangiliklar</a></li>
          <li class="yordamchi"><a href="#">talabalar</a></li>
          <li class="yordamchi"><a href="#">abituriyent</a></li>
          <li class="yordamchi"><a href="#">hujjatlar</a></li>
        </ul>
      </div>
      <div class="one_third">
        <h6 class="heading">Savol yuborish</h6>
        <form method="post" action="#">
          <fieldset>
            <textarea name="savol" id="savol" cols="30" rows="5" placeholder="Savol kiritish joyi..."></textarea>
            <button style="margin: 20px 65px; border-radius: 5px;" type="submit"
              value="submit">yuborish</button><br><br>
            <h6 class="heading">bizning ijtimoiy tarmoqlar</h6>
            <ul class="faico clear">
              <li><a style="border-radius: 50% !important;" class="faicon-dribble" href="#"><i
                    class="fab fa-telegram"></i></a></li>
              <li><a style="border-radius: 50% !important;" class="faicon-facebook" href="#"><i
                    class="fab fa-facebook"></i></a></li>
              <li><a style="border-radius: 50% !important;" class="faicon-google-plus" href="#"><i
                    class="fab fa-instagram"></i></a></li>
              <li><a style="border-radius: 50% !important;" class="faicon-twitter" href="#"><i
                    class="fab fa-twitter"></i></a></li>
              <li><a style="border-radius: 50% !important;" class="faicon-vk" href="#"><i class="fab fa-vk"></i></a>
              </li>
            </ul>
          </fieldset>
        </form>
      </div>
      <!-- ################################################################################################ -->
    </footer>
  </div>
  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
  <div class="wrapper row5" style="background-color: lightslategray;">
    <div id="copyright" class="hoc clear">
      <!-- ################################################################################################ -->
      <p class="fl_left" style="color: white;">Copyright &copy; Bobur Amirov - <a href="#"
          style="background-color: lightslategray; color: white;">Texnikum</a></p>
      <p class="fl_right" style="color: white;"><a href="#" style="background-color: lightslategray; color: white;"><i
            class="fas fa-phone"></i> +998 97 927 69
          23</a></p>
      <!-- ################################################################################################ -->
    </div>
  </div>
  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
  <a id="backtotop" href="#top"><i class="fas fa-chevron-up"></i></a>
  <!-- JAVASCRIPTS -->

  <script src="{% static 'scripts/jquery.min.js' %}"></script>
  <script src="{% static 'scripts/jquery.backtotop.js' %}"></script>
  <script src="{% static 'scripts/jquery.mobilemenu.js' %}"></script>
  <script src='https://kit.fontawesome.com/a076d05399.js'></script>

</body>

</html>

texnikumapp/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Bosh sahifa {% endblock %}

{% block content %}

<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<div >
	<!-- /*style="background-image:url('images/demo/backgrounds/01.png');"*/ -->
	<video src=" {% static 'video/135.mp4' %}"
	 autoplay loop="" width="100%"></video>
</div>
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<div class="wrapper row3">
	<main class="hoc container clear">
		<!-- main body -->
		<!-- ################################################################################################ -->
		<div class="sectiontitle">
			<h4 class="heading">Texnikumdan foto lavhalar</h4>
		</div>
		<ul class="nospace group overview">
			{% for foto in fotolar %}
			<li class="one_third">
				<figure><a href="#"><img src="{{foto.rasmlar.url}}" alt=""></a>
					<figcaption>
						<h6 class="heading">{{foto.name}}</h6>
						<p>Samarqand davlat universiteti qoshidagi Jomboy raqamli texnologiyalar texnikumi</p>
					</figcaption>
				</figure>
			</li>
			{% endfor %}

		</ul>
		<!-- ################################################################################################ -->
		<!-- / main body -->
		<div class="clear"></div>
	</main>
</div>
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<div class="wrapper row2">
	<section class="hoc container clear">
		<!-- ################################################################################################ -->
		<div class="sectiontitle">
			<h6 class="heading">Texnikum statistikasi</h6>
		</div>
		<div class="group center">
			<article class="one_third first"><a class="ringcon btmspace-50" href="#"><i class="fas fa-user-tie"></i></a>
				<h6 class="heading">Xodimlar soni</h6>
				<p class="stat">30</p>
			</article>
			<article class="one_third"><a class="ringcon btmspace-50" href="#"><i class="fas fa-user-graduate"></i></a>
				<h6 class="heading">Talabalar soni</h6>
				<p class="stat">250</p>
			</article>
			<article class="one_third"><a class="ringcon btmspace-50" href="#"><i class="fas fa-text-width"></i></a>
				<h6 class="heading">Yo'nalishlar soni</h6>
				<p class="stat">3</p>
			</article>
		</div>
		<!-- ################################################################################################ -->
	</section>
</div>
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<div class="wrapper gradient">
	<section id="testimonials" class="hoc container clear">
		<!-- ################################################################################################ -->
		<div class="sectiontitle">
			<h6 class="heading">E'lonlar</h6>
		</div>
			{% for elon in elon1 %}
				<article class="one_third first">
					<blockquote>
						<h2>{{elon.sarlavha}}</h2>
						{{elon.matn|truncatechars:100}}
						<br><span style="padding-left: 200px; color: blue;">{{elon.sana}}</span>
						<a class="btn btn-default" href="{% url 'texapp:elon' elon.id %}">Batafsil</a>
					</blockquote>
				</article>
			{% endfor %}
			{% for elon in elonlar %}
				<article class="one_third">
					<blockquote>
						<h2>{{elon.sarlavha}}</h2>
						{{elon.matn|truncatechars:100}}
						<br><span style="padding-left: 200px; color: blue;">{{elon.sana}}</span>
						<a class="btn btn-default" href="{% url 'texapp:elon' elon.id %}">Batafsil</a>
					</blockquote>
				</article>
			{% endfor %}
			<div class="sectiontitle">
				<a href="{% url 'texapp:elonlar' %}">Barchasi</a>
			</div>
		
		<!-- ################################################################################################ -->
	</section>
</div>
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<div class="wrapper row2">
	<section id="latest" class="hoc container clear">
		<!-- ################################################################################################ -->
		<div class="sectiontitle">
			<h6 class="heading">So'ngi yangiliklar</h6>
		</div>
		<ul class="nospace group">
			{% for yangilik in yangilik1 %}
			<li class="one_third first">
				<article>
					<figure><a href="#"><img src="{{yangilik.rasm.url}}" alt=""></a>
						<figcaption>
							<time datetime="2045-04-06T08:15+00:00"><strong>{{yangilik.sana|date:'d'}}</strong> <em>{{yangilik.sana|date:'M'}}</em></time>
						</figcaption>
					</figure>
					<div class="excerpt">
						<h6 class="heading">{{yangilik.sarlavha}}</h6>
						<p>Sana: {{yangilik.sana}}</p>
						<p> {{yangilik.matn|truncatechars:100}} [<a href="#">&hellip;</a>]</p>
						<footer><a class="btn" href="{% url 'texapp:yangilik' yangilik.id %}">Batafsil</a></footer>
					</div>
				</article>
			</li>
			{% endfor %}
			{% for yangilik in yangiliklar %}
			<li class="one_third">
				<article>
					<figure><a href="#"><img src="{{yangilik.rasm.url}}" alt=""></a>
						<figcaption>
							<time datetime="2045-04-06T08:15+00:00"><strong>{{yangilik.sana|date:'d'}}</strong> <em>{{yangilik.sana|date:'M'}}</em></time>
						</figcaption>
					</figure>
					<div class="excerpt">
						<h6 class="heading">{{yangilik.sarlavha}}</h6>
						<p>Sana: {{yangilik.sana}}</p>
						<p> {{yangilik.matn|truncatechars:100}} [<a href="#">&hellip;</a>]</p>
						<footer><a class="btn" href="{% url 'texapp:yangilik' yangilik.id %}">Batafsil</a></footer>
					</div>
				</article>
			</li>
			{% endfor %}
		</ul>
		<div class="sectiontitle">
			<a href="{% url 'texapp:yangiliklar' %}">Barchasi</a>
		</div>
		<!-- ################################################################################################ -->
	</section>
</div>


{% endblock %}